"""add sent_notifications table

Revision ID: 9c52cda029ac
Revises: 574d9634341b
Create Date: 2026-06-28 17:34:48.386631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c52cda029ac'
down_revision: Union[str, Sequence[str], None] = '574d9634341b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issue_url', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_notifications_id'), 'sent_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_sent_notifications_issue_url'), 'sent_notifications', ['issue_url'], unique=False)
    op.create_index(op.f('ix_sent_notifications_user_id'), 'sent_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_notifications_user_id'), table_name='sent_notifications')
    op.drop_index(op.f('ix_sent_notifications_issue_url'), table_name='sent_notifications')
    op.drop_index(op.f('ix_sent_notifications_id'), table_name='sent_notifications')
    op.drop_table('sent_notifications')
    # ### end Alembic commands ###
